[unix_http_server]
file=/run/supervisor/supervisor.sock
chmod=0700

[supervisord]
nodaemon=true
user=root
pidfile=/run/supervisor/supervisord.pid
logfile=/var/log/supervisor/supervisord.log

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/supervisor/supervisor.sock

[program:laravel-scheduler]
command=/bin/bash -c "while true; do php /var/www/html/artisan schedule:run --verbose --no-interaction; sleep 60; done"
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/scheduler.log
stderr_logfile=/var/log/supervisor/scheduler_err.log
user=www-data

[program:laravel-worker]
command=php /var/www/html/artisan queue:work --sleep=3 --tries=1 --timeout=3600 --memory=512
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/log/supervisor/worker.log
stopwaitsecs=3630
stopasgroup=true
killasgroup=true

[program:nats-consumer]
command=php /var/www/html/artisan nats:consume
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/log/supervisor/nats_consumer.log
stopwaitsecs=30

[program:outbox-publisher]
command=php /var/www/html/artisan outbox:publish --forever
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/log/supervisor/outbox_publisher.log
stopwaitsecs=15
